apiVersion: v1
kind: Service
metadata:
  name: eventbus
  labels:
    app: eventbus
spec:
  type: NodePort
  selector:
    app: eventbus
  ports:
    - name: eventbus
      protocol: TCP
      port: 4005
      targetPort: 4005